# Default values for teranode-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Deployment of the teranode-operator
deployment:
  env:
    # watch_namespace should be set to a comma separated string containing all namespaces to be watched by the operator
    # for example `watch_namespace: "teranode-dev, teranode-test, teranode-prod"` etc.
    watch_namespace:
  image:
    repository: ghcr.io/bsv-blockchain/teranode-operator
    tag: v0.2.0
    pullPolicy: Always
  replicaCount: 1

# Image of Teranode to be used when deploying with sample cluster below
teranode:
  image:
    repository: ghcr.io/bsv-blockchain/teranode
    tag: v0.11.24

# Sample Teranode cluster
sampleCluster:
  enable: false
  network: testnet
  hostname:
